"""fixed db-url

Revision ID: 4614be38d49e
Revises: db84cfe41cec
Create Date: 2023-07-10 01:39:14.630369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4614be38d49e'
down_revision = 'db84cfe41cec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
